name:  Publicar Página Web en Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name:  Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name:  Instalar Surge
        run: npm install --global surge

      - name:  Publicar la página en Surge
        run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_API_KEY }}
